# docker run -it --rm -p 3000:3000 -v /app/node_modules -v ${PWD}:/app -e CHOKIDAR_USEPOLLING=true jefsolis/frontend
# docker run -it jefsolis/frontend npm run test
# docker compose -f docker-compose-dev.yml up

FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]